### ISSUE TITLE
Dockerfile creation via Rigel

### ISSUE THREAD

**Issue by Kazadhum** [Kazadhum/atom#1]
First goal is to have Rigel create a Dockerfile for ATOM using:

> `rigel run job dockerfile`

**Comment by Kazadhum** [comment]
ran into a problem using this [Rigelfile](https://github.com/Kazadhum/my_atom/blob/1-dockerfile-creation-via-rigel/Rigelfile).

running the `rigel run job dockerfile` command results in the following:

> `WARNING - Press CTRL-C / CTRL-Z to stop execution
> Connecting to providers
> Working with application 'atom'
> ERROR - An error occurred while validating Pydantic model: 1 validation error for PluginModel
> run
>   extra fields not permitted (type=value_error.extra).`

**Comment by rarrais** [comment]
@MisterOwlPT maybe @Kazadhum requires help setting up [poetry](https://python-poetry.org/)?

**Comment by MisterOwlPT** [comment]
This doesn't seem to be a problem concerning software dependencies.

Instead, this problem arises whenever a developer:
- Doesn't provide all fields required by a plugin;
- **Passes unsupported fields to a plugin**;
- Passes wrong data types to a plugin.

You can consult required / optional fields and their expected type for _this_ plugin [here](https://github.com/rigel-ros/rigel/blob/develop/rigel/plugins/core/dockerfile/models.py#L25) 

It seems that no field "run" is supported - it should be "docker_run" instead. 
I apologize to @Kazadhum for accidentally providing an invalid Rigelfile 😞 

For future reference, here are the models for all default Rigel plugins:
- [_Dockerfile_ plugin](https://github.com/rigel-ros/rigel/blob/develop/rigel/plugins/core/dockerfile/models.py#L25) 
- [_BuildX_ plugin](https://github.com/rigel-ros/rigel/blob/develop/rigel/plugins/core/buildx/models.py#L12)
- [_LocalTest_ plugin](https://github.com/rigel-ros/rigel/blob/develop/rigel/plugins/core/test/models.py#L15)
- [_RoboMaker_ plugin](https://github.com/rigel-ros/rigel/blob/develop/rigel/plugins/aws/robomaker/models.py#L112)

**Comment by Kazadhum** [comment]
Thank you @MisterOwlPT, it now runs as expected :)

**Comment by Kazadhum** [comment]
I'm having trouble understanding the `entrypoint` part, specifically this line:

`- "export WORKSPACE_INSTALL=~/ros_workspace/install"`

I don't understand what this is supposed to be, as 'catkin_make' doesn't create this directory. Maybe this is specific to colcon? If so, perhaps I don't need to export this variable, right?

**Comment by rarrais** [comment]
Yes, the ```install``` folder is specific to the colcon builder. For 'catkin_make' you either have to build in such a way that the install folder is generated (by configuring the compilation flags), or alternatively (and more easy) you have to adapt this line to the following:

```
- "export WORKSPACE_INSTALL=~/ros_workspace/devel"
```

**Comment by Kazadhum** [comment]
Thank you, professor, I've changed that now. As such, I think the `dockerfile` field is almost complete. If I'm not mistaken, I need only create a `.rosinstall` file and change the `docker_run` field. Meanwhile, I'll move on to #2 so I can test all of this.
