### ISSUE TITLE
Build ATOM image using Rigel

### ISSUE THREAD

**Issue by Kazadhum** [Kazadhum/atom#2]
Second goal is to have Rigel create a Docker image for ATOM, using:

>`rigel run job build`

Or, with the sequence properly defined:

>`rigel run sequence deploy`

**Comment by Kazadhum** [comment]
Ran into 3 problems when building:

- Couldn't build because buildx wasn't installed (fixed);

- Error when cloning a public repo from github (I can clone the repo normally onto my local workspace):

```
------                                                                                                   
 > [stage-1 23/33] RUN git clone https://github.com/miguelriemoliveira/rviz:                             
#0 0.139 /bin/sh: 1: git: not found                                                                      
------
Dockerfile:62
--------------------
  60 |     RUN mkdir -p ~/ros_workspace/src
  61 |     RUN cd ~/ros_workspace/src
  62 | >>> RUN git clone https://github.com/miguelriemoliveira/rviz
  63 |     
  64 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/miguelriemoliveira/rviz" did not complete successfully: exit code: 127


```
- Error when running `catkin_make`, after commenting the `git clone` line:

```
Dockerfile:82
--------------------
  81 |     # Compile ROS workspace.
  82 | >>> RUN /bin/bash -c "source /opt/ros/noetic/setup.bash \ 
  83 | >>>     && cd /home/rigeluser/ros_workspace \
  84 | >>>     
  85 | >>>     && sudo rosdep fix-permissions \
  86 | >>>     && rosdep update \
  87 | >>>     && rosdep install --rosdistro noetic --from-paths src --ignore-src -r -y \
  88 | >>>     && catkin_make "
  89 |         
--------------------
ERROR: failed to solve: process "/bin/sh -c /bin/bash -c \"source /opt/ros/noetic/setup.bash     && cd /home/rigeluser/ros_workspace     && sudo rosdep fix-permissions     && rosdep update     && rosdep install --rosdistro noetic --from-paths src --ignore-src -r -y     && catkin_make \"" did not complete successfully: exit code: 1

```

**Comment by Kazadhum** [comment]
The issue with the `git clone` line is fixed: I forgot to include `git` in the `apt` field.

**Comment by Kazadhum** [comment]
By spinning up a ros:noetic container and running the commands one at a time, I was able to pinpoint the cause of some of the issues here. 

- The RViz repo was being cloned to the wrong path;
- "qtbase5-dev" and "qtdeclarative5-dev" needed to be installed using `apt`;

Both of these led to an error when running `catkin_make` and have been fixed.

When running `rigel run sequence deploy`, with `deploy: ["dockerfile", "build"]`, a different error pops up, though. By doing this in another container from scratch, I saw that it happens when running `rosdep install --rosdistro noetic --from-paths src --ignore-src -r -y`. It returns:

```
#0 174.8 ERROR: the following packages/stacks could not have their rosdep keys resolved
#0 174.8 to system dependencies:
#0 174.8 atom_core: No definition of [python-matplotlib] for OS version [focal]
#0 174.8 Continuing to install resolvable dependencies...
#0 174.8 ERROR: the following rosdeps failed to install
#0 174.8   apt: command [sudo -H apt-get install -y python-rospkg] failed
#0 174.8   apt: command [sudo -H apt-get install -y python-colorama] failed
#0 174.8   apt: command [sudo -H apt-get install -y python-scipy] failed
#0 174.8   apt: command [sudo -H apt-get install -y python-opencv] failed
#0 174.8   apt: command [sudo -H apt-get install -y python-networkx] failed
#0 174.8   apt: command [sudo -H apt-get install -y python-pandas] failed
#0 174.8   apt: Failed to detect successful installation of [python-rospkg]
#0 174.8   apt: Failed to detect successful installation of [python-colorama]
#0 174.8   apt: Failed to detect successful installation of [python-scipy]
#0 174.8   apt: Failed to detect successful installation of [python-opencv]
#0 174.8   apt: Failed to detect successful installation of [python-networkx]
#0 174.8   apt: Failed to detect successful installation of [python-pandas]
```

I think this is because i need to install the `python3-*` packages, instead of the `python-*` version, though I am not sure of how to do this.

**Comment by Kazadhum** [comment]
I fixed it! The package.xml files in the various ATOM packages listed their dependencies like this:

```
  <exec_depend>python-rospkg</exec_depend>
  <exec_depend>python-colorama</exec_depend>
  <exec_depend>python-jinja2</exec_depend>
  <exec_depend>python-numpy</exec_depend>
  <exec_depend>python-yaml</exec_depend>
  <exec_depend>python-graphviz-pip</exec_depend>
```

`apt` wasn't finding these packages. Changed these to:

```
  <exec_depend>python3-rospkg</exec_depend>
  <exec_depend>python3-colorama</exec_depend>
  <exec_depend>python3-jinja2</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python3-graphviz-pip</exec_depend>
```
Afterwards, Docker built the image just fine. 

@miguelriemoliveira I don't know if this is something that is supposed to happen or if this is an appropriate fix, since I made changes to files in the ATOM packages. What do you think, professor?

**Comment by Kazadhum** [comment]
Ran into another issue when including a command: `command: "roslaunch t2rgb.launch"`

When running the container, it can't find the launch file.

```
ROS_VERSION=1
WORKSPACE_INSTALL=/home/rigeluser/ros_workspace/devel
PKG_CONFIG_PATH=/home/rigeluser/ros_workspace/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig
ROS_PYTHON_VERSION=3
HOSTNAME=803dbc03c573
ROS_PACKAGE_PATH=/home/rigeluser/ros_workspace/src:/opt/ros/noetic/share
ROSLISP_PACKAGE_DIRECTORIES=/home/rigeluser/ros_workspace/devel/share/common-lisp
PWD=/home/rigeluser/ros_workspace
HOME=/home/rigeluser
LANG=C.UTF-8
ROS_ETC_DIR=/opt/ros/noetic/etc/ros
ROS_BAGS=/home/rigeluser/bagfiles
CMAKE_PREFIX_PATH=/home/rigeluser/ros_workspace/devel:/opt/ros/noetic
PYTHONPATH=/home/rigeluser/ros_workspace/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages
SHLVL=1
ROS_MASTER_URI=http://localhost:11311
ATOM_DATASETS=/home/rigeluser/datasets
LD_LIBRARY_PATH=/home/rigeluser/ros_workspace/devel/lib:/opt/ros/noetic/lib
LC_ALL=C.UTF-8
PATH=/opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ROS_ROOT=/opt/ros/noetic/share/ros
ROS_DISTRO=noetic
OLDPWD=/
_=/usr/bin/printenv
RLException: [t2rgb.launch] is not a launch file name
The traceback for the exception was written to the log file
```

**Comment by Kazadhum** [comment]
Seems one issue was that the repos were being cloned to the wrong directory. This has been fixed.
Besides, `ros_workspace/devel/setup.bash` wasn't being sourced correctly. I tried to apply to source it using the `entrypoint` field but it didn't work. This is what I used:

```
entrypoint:
            - "if [[ -f \"/usr/share/$GAZEBO_VERSION/setup.sh\" ]]; then source /usr/share/$GAZEBO_VERSION/setup.sh; fi"
            - "export WORKSPACE_INSTALL=~/ros_workspace/devel"
            - export ROS_BAGS="$HOME/bagfiles"
            - export ATOM_DATASETS="$HOME/datasets"
            - source $WORKSPACE_INSTALL/setup.bash
```

Another problem that came up is that the Gazebo GUI doesn't open and when, inside a container, I try to launch via the `t2rgb.launch`, which simply brings the robot up in an empty gazebo environment, it crashes, resulting in:

```
[gazebo_gui-3] process has died [pid 1034, exit code 134, cmd /opt/ros/noetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/home/rigeluser/.ros/log/32addc4c-ba16-11ed-87df-0242ac110002/gazebo_gui-3.log].
log file: /home/rigeluser/.ros/log/32addc4c-ba16-11ed-87df-0242ac110002/gazebo_gui-3*.log
[spawn_urdf-5] process has finished cleanly
log file: /home/rigeluser/.ros/log/32addc4c-ba16-11ed-87df-0242ac110002/spawn_urdf-5*.log
^C[robot_state_publisher-4] killing on exit
[gazebo-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum 

@miguelriemoliveira I don't know if this is something that is supposed to happen or if this is an appropriate fix, since I made changes to files in the ATOM packages. What do you think, professor?

Not sure. The best is to test. @manuelgitgomes what do you think? Would it work for you like this?

**Comment by miguelriemoliveira** [comment]
> Another problem that came up is that the Gazebo GUI doesn't open and when, inside a container, I try to launch via the t2rgb.launch, which simply brings the robot up in an empty gazebo environment, it crashes, resulting in:

Hum, can you run xwindows in your container? Is it because of the lack of graphical stuff?
How to you login to the docker image? An ssh?

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum ,

I think these issues are also important for all ATOM users, so I am suggesting that although you have your fork the issues are created in the base atom repo.

Sounds good?

**Comment by Kazadhum** [comment]
> > Another problem that came up is that the Gazebo GUI doesn't open and when, inside a container, I try to launch via the t2rgb.launch, which simply brings the robot up in an empty gazebo environment, it crashes, resulting in:
> 
> Hum, can you run xwindows in your container? Is it because of the lack of graphical stuff? How to you login to the docker image? An ssh?

I think I can can xwindows. I start the container with:
`xhost +`
`docker run -it --net=host --env DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix atom:latest bash`

If I'm not mistaken, this mounts the X11 volume in the container and passes the display as a env variable, so I don't know what could be wrong here. From what I gather, it is an error concerning the GUI. But it does run without the GUI, so maybe this is something that is already handled by Rigel in the `test` sequence. I'll try verifying that today.



> Hi @Kazadhum ,
> 
> I think these issues are also important for all ATOM users, so I am suggesting that although you have your fork the issues are created in the base atom repo.
> 
> Sounds good?

Sounds good! I'll replicate those issues and try to link them to this fork and issues.

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira and @Kazadhum!

> Not sure. The best is to test. @manuelgitgomes what do you think? Would it work for you like this?

Honestly, I agree it should be test, but I have a feeling it might work.

On my machine I have some on `python` only (`jinja2`), some only in `python3` (`colorama`, `rospkg`), some in both (`yaml`, `numpy`) and some not at all (`graphviz-pip`).

**Comment by miguelriemoliveira** [comment]
> Sounds good! I'll replicate those issues and try to link them to this fork and issues.

No need to replicate. I think there is an option to transfer... Try to do it and if you can't let me know ... may need permissions on ATOM's side ...

**Comment by miguelriemoliveira** [comment]
> I think I can can xwindows. I start the container with:

him, but once you have  terminal in the contained can you launch a graphical application? RViz, rqt, something?
Does it work?

One option to try is to run gazebo in non graphical mode ... there is a flag for that ...

**Comment by Kazadhum** [comment]
> > Sounds good! I'll replicate those issues and try to link them to this fork and issues.
> 
> No need to replicate. I think there is an option to transfer... Try to do it and if you can't let me know ... may need permissions on ATOM's side ...

Hello, @miguelriemoliveira! It looks like you can only transfer issues between repos that belong to the same user...

![image](https://user-images.githubusercontent.com/93128909/223118754-fa7462b9-3538-46dd-99e2-1fea8da3c7ff.png)

**Comment by Kazadhum** [comment]
> > I think I can can xwindows. I start the container with:
> 
> him, but once you have terminal in the contained can you launch a graphical application? RViz, rqt, something? Does it work?
> 
> One option to try is to run gazebo in non graphical mode ... there is a flag for that ...

Ok, so I just tried rqt and it works. I need to update the Rigelfile to include it (I just installed rqt directly in a container in order to test this) but the rqt GUI does work. So it would appear the problem lies with Gazebo itself. Launching `t2rgb.launch` with the flag `gui:=false` works, too, so it must be an issue with the gazebo GUI, specifically

**Comment by rarrais** [comment]
Hi @Kazadhum , I'm tagging @sergiodmlteixeira and @MisterOwlPT so they can follow the conversation. We have analysed the issue related to the GUI of Gazebo not showing. @sergiodmlteixeira will shortly follow with a suggestion. 

In the future, if you are facing issues and think that we might help, please tag us on the issue.

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum ,

but you have write permission to ATOM

![image](https://user-images.githubusercontent.com/11350998/223191109-281586a7-e3bf-4e86-9b42-9e6f72a9fafc.png)


Give me write permission to your fork and I can try to ...

**Comment by Kazadhum** [comment]
Hi professor @miguelriemoliveira. I believe you already have write permissions to this fork, since you're a collaborator and this repo is public. From what I can see, I can only control the type of access collaborators have by creating an organization.

![image](https://user-images.githubusercontent.com/93128909/223195055-01d0944b-9391-4424-aa83-5decd4ed1cf3.png)

**Comment by Kazadhum** [comment]
> Hi @Kazadhum , I'm tagging @sergiodmlteixeira and @MisterOwlPT so they can follow the conversation. We have analysed the issue related to the GUI of Gazebo not showing. @sergiodmlteixeira will shortly follow with a suggestion.
> 
> In the future, if you are facing issues and think that we might help, please tag us on the issue.

Thank you professor @rarrais. I thought all collaborators were notified even without tagging... Thank you for the heads-up!

**Comment by miguelriemoliveira** [comment]
Hi @Kazadhum ,

I tried to transfer but could not do it. I think the problem is that ATOM is not on my user but in lardemua. The onlt solution would be to change the forks owner to [lardemua](https://github.com/lardemua), and only then a transfer would be possible, I think.

But that's overcomplicating. I say, the next issues create them on ATOM main, these ones leave them here.

**Comment by Kazadhum** [comment]
> Hi @Kazadhum ,
> 
> I tried to transfer but could not do it. I think the problem is that ATOM is not on my user but in lardemua. The onlt solution would be to change the forks owner to [lardemua](https://github.com/lardemua), and only then a transfer would be possible, I think.
> 
> But that's overcomplicating. I say, the next issues create them on ATOM main, these ones leave them here.

Sounds good! Thank you, professor!

**Comment by sergiodmlteixeira** [comment]
Hi @Kazadhum, sorry for the delay,

I think your problem with Gazebo GUI might not be related with Docker or Rigel graphical interface (as you already verified by using rqt), but I think it might be related to your gazebo configuration on the Rigelfile being incomplete.

I would make two suggestions:

1- On your Rigelfile, on your dockerfile plugin configuration (around line 32), you should add an environment variable stating the gazebo version you are using:

```
env:
    - name: GAZEBO_VERSION
      value: gazebo-11
```

2- On the same dockerfile plugin configuration, try adding to your entrypoint parameter the export of the gazebo model and resource path, with the paths to your meshes, models and textures. In my case it looks like something like this:

```
entrypoint:
    - 'if [[ -f "/usr/share/$GAZEBO_VERSION/setup.sh" ]]; then source /usr/share/$GAZEBO_VERSION/setup.sh; fi'
    - "export GAZEBO_RESOURCE_PATH=$GAZEBO_RESOURCE_PATH/home/robomaker/ros_workspace/install/tm_sim_gazebo/share/tm_sim_gazebo:"
    - "export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH/home/robomaker/ros_workspace/install/tm_sim_gazebo/share/tm_sim_gazebo/meshes:
```

I think your problem might be related to Gazebo GUI not finding your meshes/models, because i had problems like these in the past where Gazebo GUI was crashing, just like in your case, and it was because it could not find the 3D models.

**Comment by Kazadhum** [comment]
Thank you @sergiodmlteixeira! It works as intended now.
